# # -*- coding: utf-8 -*-
# """RFmodel.ipynb

# Automatically generated by Colaboratory.

# Original file is located at
#     https://colab.research.google.com/drive/1osYBmutEb7uJdyg0em1x1NE4KrFPsAdi
# """

import pickle


import pandas as pd
import io
df = pd.read_csv('Dataset.csv')
print(df)

print(df.shape)

dir(df)

df.head()

df.wCategory

df.hCategory

df.columns

df.index

df['wCategory']

X = df.drop(['date','name','wCategory', 'sex', 'pid'], axis=1)
y = df.wCategory


df.isnull().sum()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

len(X_train)

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)

model.score(X_test, y_test)

y_predicted = model.predict(X_test)

"""Confusion matrix"""

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_predicted)
cm

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sn
plt.figure(figsize=(10,7))
sn.heatmap(cm, annot=True)
plt.xlabel('Predicted')
plt.ylabel('Truth')

import pickle

from sklearn.naive_bayes import MultinomialNB
classifier_multi = MultinomialNB()
classifier_multi.fit(X_train, y_train)

classifier_multi.score(X_test, y_test)
print('Accuracy is',model.score(X_test, y_test)*100, '%')

pickle.dump(model, open('random_forest.sav','wb'))

pickle.dump(classifier_multi, open('classifier.sav','wb'))

