# Generated by Django 4.0 on 2022-01-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('fname', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('wCategory', models.IntegerField()),
                ('height', models.CharField(max_length=200)),
                ('hCategory', models.IntegerField()),
                ('bFeeding', models.CharField(max_length=200)),
                ('suppliment', models.CharField(max_length=200)),
                ('development', models.CharField(max_length=200)),
            ],
        ),
    ]
