# Generated by Django 4.0 on 2022-01-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterhealth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
    ]
