# Generated by Django 3.2.9 on 2022-01-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterhealth', '0002_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordinfo',
            name='bFeeding',
        ),
        migrations.RemoveField(
            model_name='recordinfo',
            name='development',
        ),
        migrations.RemoveField(
            model_name='recordinfo',
            name='suppliment',
        ),
        migrations.AlterField(
            model_name='recordinfo',
            name='hCategory',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recordinfo',
            name='wCategory',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recordinfo',
            name='weight',
            field=models.IntegerField(max_length=200),
        ),
    ]
