# Generated by Django 3.2.9 on 2022-01-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterhealth', '0004_auto_20220122_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordinfo',
            name='pid',
        ),
        migrations.AddField(
            model_name='recordinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordinfo',
            name='patient',
            field=models.IntegerField(default='0'),
        ),
    ]
