# Generated by Django 4.0 on 2022-01-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterhealth', '0005_auto_20220122_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordinfo',
            name='patient',
        ),
        migrations.AddField(
            model_name='recordinfo',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
