# Generated by Django 4.0 on 2022-01-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterhealth', '0006_remove_recordinfo_patient_recordinfo_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.CharField(max_length=200)),
                ('fname', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('cname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('residence', models.CharField(max_length=200)),
            ],
        ),
    ]
