# Generated by Django 4.0 on 2022-01-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterhealth', '0007_childinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordinfo',
            name='weight',
            field=models.CharField(max_length=200),
        ),
    ]
