# Generated by Django 4.0 on 2022-01-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterhealth', '0008_alter_recordinfo_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordinfo',
            name='sex',
            field=models.CharField(default='', max_length=200),
        ),
    ]
