# Generated by Django 4.0 on 2022-01-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterhealth', '0009_recordinfo_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('fname', models.CharField(max_length=200)),
                ('nid', models.CharField(max_length=200)),
                ('diagnosis', models.CharField(max_length=200)),
            ],
        ),
    ]
